Harshita Jain,
 E20CSE470,
  Eb31,
   Lab 1

PART A

In [ ]:
#import numpy


In [ ]:
import numpy as np;
#version of numpy
print(np.__version__)

1.21.6


In [19]:
#create 1D Array
Arr=np.array([10,20,30,40])
print(Arr)
# Type of Arr
print(type(Arr))
# Dimension Arr
print(Arr.ndim)
#printing item size
print(Arr.itemsize)


[10 20 30 40]
<class 'numpy.ndarray'>
1
8


In [ ]:
Arr[3]

40

In [18]:
#creating 2D array

Arra=np.array([[10,20,30], [1,2,3], [4,5,6]])
print(Arra)
#Type of Arra
print(type(Arra))
# Matrix (n*n)
print(np.shape(Arra))
#Dimension of Arra
a =Arra.ndim 
print(a)
#printing Item Size
print(Arra.itemsize)

[[10 20 30]
 [ 1  2  3]
 [ 4  5  6]]
<class 'numpy.ndarray'>
(3, 3)
2
8


In [ ]:
#Slicing
A = np.array ([4, 5, 6, 3, 9, 7])
print(A[2:5])   

[6 3 9]


In [ ]:
# Slicing in 2D 
Aaa = np.array([[1, 2, 3],[4, 5, 6]])
Aaa[0:1,0:2]

array([[1, 2]])

In [ ]:
M = np.array([4,5,6,7]) 
N = np.array([3,4,1])
np.concatenate([M, N])

array([4, 5, 6, 7, 3, 4, 1])

In [20]:
Aaa = np.array([[1, 2, 3],[4, 5, 6]])
Aaaa=Aaa
# reshaping the array
print(Aaaa.reshape(3,2))
Aa = np.array([[10, 20, 30],[40, 50, 60]])
#axis define in which way we should concate 
#1 = vertical and 0 = Horizontal
np.concatenate([Aaa,Aa],axis=0)


[[1 2]
 [3 4]
 [5 6]]


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [10, 20, 30],
       [40, 50, 60]])

In [21]:
#spliting the array in 3
Arrrr = ([4, 5, 6, 3, 9,])
print(np.array_split(Arrrr,3))

[array([4, 5]), array([6, 3]), array([9])]


In [24]:
Ad = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9],[10, 11, 12]] )
print(np.array_split(Ad,3))

[array([[1, 2, 3],
       [4, 5, 6]]), array([[7, 8, 9]]), array([[10, 11, 12]])]


In [ ]:
Dd = np.array([1, 2, 3, 4, 5, 4, 4])
Ddd = np.where(Dd==4)
#where is used for geting the index of a particular element 
print(Ddd)

(array([3, 5, 6]),)


In [ ]:
Hh =np.array([[ 1, 2, 3],[ 4, 5, 6],[ 7, 8, 9],[10, 11, 12]])
Hhh = np.where(Hh==5)
#getting the index of 5 in 2D array
print(Hhh)

(array([1]), array([1]))


In [ ]:
 Xx = np.array([1, 2, 3, 4, 5, 6, 7, 8])
 for i in Xx:
  if i%2==0:
    print ("This is even and index is ", np.where(Xx==i))
  else:
    print("This is Odd and index is " ,np.where(Xx==i))


This is Odd and index is  (array([0]),)
This is even and index is  (array([1]),)
This is Odd and index is  (array([2]),)
This is even and index is  (array([3]),)
This is Odd and index is  (array([4]),)
This is even and index is  (array([5]),)
This is Odd and index is  (array([6]),)
This is even and index is  (array([7]),)


In [ ]:
Mn = np.array([6, 5, 1, 2, 9, 10, 36, 7])
#sorting in asending order 
MM = np.sort(Mn)
print(MM)
#sorting in decending order
Nn=-np.sort(-Mn)
print(Nn)

[ 1  2  5  6  7  9 10 36]
[36 10  9  7  6  5  2  1]


In [ ]:
Ee = np.array( [[5, 3, 7], [8, 10, 6], [40, -2, 7]] )
Eee = np.sort(Ee)
print(Eee)

[[ 3  5  7]
 [ 6  8 10]
 [-2  7 40]]


In [ ]:
from numpy import random
# we import random function for getting random numbers in array
xy=random.randint(20, size=(6))

print(xy)

[ 2 15 14  6 18 16]


In [ ]:
xyy=random.randint(50, size=(3,5))
# for 2D array
print(xyy)

[[43 44 45 32 18]
 [16 49 12 32 27]
 [ 4 15 46 31 43]]


In [ ]:
xry=random.rand(6)
# float random 
print(xry)

[0.83938966 0.18219668 0.87904468 0.11243191 0.11807889 0.64387814]


In [ ]:
xyry=random.rand(3,5)
# float random 
print(xyry)

[[0.28596185 0.17035224 0.90612226 0.71101683 0.99224656]
 [0.86896254 0.73599848 0.87587658 0.86494886 0.08138836]
 [0.03280105 0.98957464 0.07947731 0.64492981 0.64849596]]


In [ ]:
Bbb = np.array( [6, 5, 1, 2, 9, 10, 36, 7])
np.random.shuffle(Bbb)
# Suffle the array
print(Bbb)

[ 6  1  5  9 10  2 36  7]


In [ ]:
Ff = np.array([[ 1, 2, 3],[ 4, 5, 6],[ 7, 8, 9],[10, 11, 12]])
np.random.shuffle(Ff)
# shuffle the 2D array
print(Ff)

[[10 11 12]
 [ 1  2  3]
 [ 7  8  9]
 [ 4  5  6]]


PART B

In [ ]:
from google.colab import files 
uploaded = files.upload()

Saving winequality-white.csv to winequality-white.csv


In [ ]:
import pandas as pd
wine_data = pd.read_csv('winequality-white.csv')
print(wine_data)

     fixed acidity;"volatile acidity";"citric acid";"residual sugar";"chlorides";"free sulfur dioxide";"total sulfur dioxide";"density";"pH";"sulphates";"alcohol";"quality"
0      7;0.27;0.36;20.7;0.045;45;170;1.001;3;0.45;8.8;6                                                                                                                     
1     6.3;0.3;0.34;1.6;0.049;14;132;0.994;3.3;0.49;9...                                                                                                                     
2     8.1;0.28;0.4;6.9;0.05;30;97;0.9951;3.26;0.44;1...                                                                                                                     
3     7.2;0.23;0.32;8.5;0.058;47;186;0.9956;3.19;0.4...                                                                                                                     
4     7.2;0.23;0.32;8.5;0.058;47;186;0.9956;3.19;0.4...                                                                                

In [15]:
WineData=wine_data.to_numpy()
#converting into array

In [16]:
np.shape(WineData)

(4898, 1)

In [17]:
Y = WineData[0:1144,-2:-1]
print(Y.shape)
print(Y)

X = WineData[0:1144,0:12]
print(X.shape)


(1144, 0)
[]
(1144, 1)
